module.exports.userValidation = require('./user.validation')
module.exports.customValidation = require('./custom.validation')
module.exports.authValidation = require('./auth.validation')
module.exports.albumValidation = require('./album.validation')
module.exports.genreValidation = require('./genre.validation')
module.exports.songValidation = require('./song.validation')