module.exports.userController = require('./user.controller')
module.exports.authController = require('./auth.controller')
module.exports.songController = require('./song.controller')
module.exports.albumController = require('./album.controller')
module.exports.genreController = require('./genre.controller')