module.exports.User = require('./user.model')
module.exports.Song = require('./song.model')
module.exports.Album = require('./album.model')
module.exports.Genre = require('./genre.model')
module.exports.Player = require('./player.model')
module.exports.PlayList = require('./playlist.model')
module.exports.Library = require('./library.model')
module.exports.Follow = require('./follow.model')